steps:
# Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/cloudrun-test-service', '.']

# Push image to registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/cloudrun-test-service']

# Deploy to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - run
  - deploy
  - cloudrun-test-service
  - --image
  - gcr.io/$PROJECT_ID/cloudrun-test-service
  - --region
  - europe-west1
  - --platform
  - managed
  - --allow-unauthenticated

images:
- gcr.io/$PROJECT_ID/cloudrun-test-service

options:
  logging: CLOUD_LOGGING_ONLY